[tools]
go = "1.26.5"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", tags = "pgx5" }
vp = "latest"

[env]
_.file = { path = ".env", redact = false }

[tasks.dev]
run = "mise run dev:be ::: dev:fe"

[tasks."dev:be"]
run = "go tool air"

[tasks."dev:fe"]
run = "bun run dev"

[tasks."docs"]
run = "go tool swag init --v3.1"

[tasks."db:create"]
usage = 'arg "[name]"'
run = "migrate create -ext sql -dir internal/db/migrations -seq ${usage_name}"

[tasks."db:up"]
run = "migrate -database pgx5://: -path internal/db/migrations up"

[tasks."db:down"]
run = "migrate -database pgx5://: -path internal/db/migrations down"
