[tools]
go = "1.26.5"
"go:github.com/golang-migrate/migrate/v4/cmd/migrate" = { version = "latest", tags = "pgx5" }
vp = "latest"

[env]
_.file = { path = ".env", redact = false }

[tasks.dev]
run = "go tool air"

[tasks."db.create"]
usage = 'arg "[name]"'
run = "migrate create -ext sql -dir internal/db/migrations -seq ${usage_name}"

[tasks."db.up"]
run = "migrate -database pgx5://: -path internal/db/migrations up"

[tasks."db.down"]
run = "migrate -database pgx5://: -path internal/db/migrations down"
