// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag/v2"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "components": {
        "securitySchemes": {
            "ApiKeyAuth": {
                "in": "header",
                "name": "Authorization",
                "type": "apiKey"
            }
        }
    },
    "info": {
        "contact": {
            "email": "suhartanto@kekkon.nexus",
            "name": "Ryan Suhartanto",
            "url": "https://github.com/ryansuhartanto/koda-b8-backend2"
        },
        "description": "{{escape .Description}}",
        "license": {
            "name": "MIT"
        },
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    },
    "paths": {},
    "openapi": "3.1.0",
    "servers": [
        {
            "url": "localhost:8080/"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Title:            "GoREST",
	Description:      "Go exercise implementing a simple REST server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
